const quotes = [
  { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { quote: "Don’t let what you cannot do interfere with what you can do.", author: "John Wooden" },
  { quote: "The expert in anything was once a beginner.", author: "Helen Hayes" },
  { quote: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
  { quote: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
  { quote: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { quote: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
  { quote: "The harder you work for something, the greater you’ll feel when you achieve it.", author: "Unknown" },
  { quote: "Dream big. Work hard. Stay humble.", author: "Unknown" },
  { quote: "Learning is not attained by chance, it must be sought for with ardor and diligence.", author: "Abigail Adams" },
  { quote: "Strive for progress, not perfection.", author: "Unknown" },
  { quote: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
  { quote: "There are no shortcuts to any place worth going.", author: "Beverly Sills" },
  { quote: "The secret to getting ahead is getting started.", author: "Mark Twain" },
  { quote: "Perseverance is not a long race; it’s many short races one after another.", author: "Walter Elliot" },
  { quote: "If you want to achieve greatness, stop asking for permission.", author: "Unknown" },
  { quote: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { quote: "Don’t limit your challenges, challenge your limits.", author: "Jerry Dunn" },
  { quote: "Mistakes are proof that you are trying.", author: "Jennifer Lim" },
  { quote: "You are capable of more than you know.", author: "Unknown" },
  { quote: "Your only limit is your mind.", author: "Unknown" },
  { quote: "If you can dream it, you can do it.", author: "Walt Disney" },
  { quote: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
  { quote: "Don’t count the days. Make the days count.", author: "Muhammad Ali" },
  { quote: "A little progress each day adds up to big results.", author: "Satya Nani" },
  { quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { quote: "It’s not about how bad you want it. It’s about how hard you’re willing to work for it.", author: "Unknown" },
  { quote: "If it doesn’t challenge you, it won’t change you.", author: "Fred DeVito" },
  { quote: "Small steps in the right direction can turn out to be the biggest step of your life.", author: "Unknown" },
  { quote: "Winners never quit and quitters never win.", author: "Vince Lombardi" },
  { quote: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
  { quote: "Be stronger than your excuses.", author: "Unknown" },
  { quote: "You don’t have to be perfect to be amazing.", author: "Unknown" },
  { quote: "Focus on your goals. Don’t look in any direction but ahead.", author: "Unknown" },
  { quote: "Success doesn’t come to you. You’ve got to go to it.", author: "Marva Collins" },
  { quote: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { quote: "Don’t wish for it, work for it.", author: "Unknown" },
  { quote: "Failure is not the opposite of success; it’s part of success.", author: "Arianna Huffington" },
  { quote: "The secret of success is to do the common things uncommonly well.", author: "John D. Rockefeller" },
  { quote: "Be so good they can’t ignore you.", author: "Steve Martin" },
  { quote: "Study hard, stay humble, and make it happen.", author: "Unknown" },
  { quote: "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
  { quote: "If you’re not willing to learn, no one can help you. If you’re determined to learn, no one can stop you.", author: "Zig Ziglar" },
  { quote: "Focus on being productive instead of busy.", author: "Tim Ferriss" },
  { quote: "Challenges are what make life interesting. Overcoming them is what makes life meaningful.", author: "Joshua Marine" },
  { quote: "A winner is a dreamer who never gives up.", author: "Nelson Mandela" },
  { quote: "Learning never exhausts the mind.", author: "Leonardo da Vinci" },
  { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
  { quote: "Don’t let yesterday take up too much of today.", author: "Will Rogers" },
  { quote: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou" },
  { quote: "Stay positive, work hard, make it happen.", author: "Unknown" },
  { quote: "A goal without a plan is just a wish.", author: "Antoine de Saint-Exupéry" },
  { quote: "Believe you can and you’re halfway there.", author: "Theodore Roosevelt" },
  { quote: "The best way to predict your future is to create it.", author: "Abraham Lincoln" },
  { quote: "Don’t be afraid to fail. Be afraid not to try.", author: "Michael Jordan" },
  { quote: "Work hard in silence, let success make the noise.", author: "Frank Ocean" },
  { quote: "Every accomplishment starts with the decision to try.", author: "John F. Kennedy" },
  { quote: "Success is no accident. It’s hard work, learning, sacrifice, and most of all, love of what you are doing.", author: "Pele" },
  { quote: "Patience and perseverance have a magical effect before which difficulties disappear.", author: "John Quincy Adams" },
  { quote: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { quote: "You don’t need to be the best, just do your best.", author: "Unknown" },
  { quote: "There’s no substitute for hard work.", author: "Thomas Edison" },
  { quote: "Every day is a new beginning. Take a deep breath and start again.", author: "Unknown" },
  { quote: "Don’t stop until you’re proud.", author: "Unknown" },
  { quote: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
  { quote: "Consistency is more important than perfection.", author: "Unknown" },
  { quote: "Success is not how high you have climbed, but how you make a positive difference.", author: "Roy T. Bennett" },
  { quote: "Work hard, stay consistent, and be patient. Your time will come.", author: "Unknown" },
  { quote: "Great things never come from comfort zones.", author: "Unknown" },
  { quote: "Success doesn’t happen overnight. Keep going.", author: "Unknown" },
  { quote: "Don’t let failure stop you. Let it teach you.", author: "Unknown" },
  { quote: "There is no elevator to success — you have to take the stairs.", author: "Zig Ziglar" },
  { quote: "Study while others are sleeping; work while others are playing.", author: "William Arthur Ward" },
  { quote: "Keep your eyes on the stars and your feet on the ground.", author: "Theodore Roosevelt" },
  { quote: "Education is not preparation for life; education is life itself.", author: "John Dewey" },
  { quote: "Push harder than yesterday if you want a different tomorrow.", author: "Unknown" },
  { quote: "Don’t compare your progress with others. We all have our own pace.", author: "Unknown" },
  { quote: "Never stop learning, because life never stops teaching.", author: "Unknown" },
  { quote: "One day, all your hard work will pay off.", author: "Unknown" },
  { quote: "Dream it. Wish it. Do it.", author: "Unknown" },
  { quote: "The key to success is to focus on goals, not obstacles.", author: "Unknown" },
  { quote: "Hard work beats talent when talent doesn’t work hard.", author: "Tim Notke" },
  { quote: "Keep going. Everything you need will come to you at the perfect time.", author: "Unknown" },
  { quote: "You’re doing better than you think.", author: "Unknown" },
  { quote: "The pain you feel today will be the strength you feel tomorrow.", author: "Unknown" },
  { quote: "Success doesn’t come from what you do occasionally, it comes from what you do consistently.", author: "Marie Forleo" },
  { quote: "Work until your idols become your rivals.", author: "Drake" },
  { quote: "Effort is like toothpaste – you can always squeeze out a little more.", author: "Unknown" },
  { quote: "Focus on the step in front of you, not the whole staircase.", author: "Unknown" },
  { quote: "You are stronger than you think and smarter than you believe.", author: "Unknown" },
  { quote: "Don’t let the fear of failure hold you back.", author: "Unknown" },
  { quote: "If you keep going, you’ll eventually get there.", author: "Unknown" },
  { quote: "Make your future self proud.", author: "Unknown" },
  { quote: "Learning is a journey, not a race.", author: "Unknown" },
  { quote: "Be patient. The best things come after hard work.", author: "Unknown" },
  { quote: "You’re not behind. You’re just building your foundation.", author: "Unknown" },
  { quote: "Great achievements start with small consistent actions.", author: "Unknown" },
  { quote: "Even the longest journey starts with a single step.", author: "Lao Tzu" },
  { quote: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { quote: "Keep your dreams alive. They’re your reason to keep pushing.", author: "Unknown" },
  { quote: "Stay focused. Ignore the noise.", author: "Unknown" },
  { quote: "Every effort you make brings you closer to your goal.", author: "Unknown" },
];

module.exports = quotes; 
